# Generated by Django 4.2.20 on 2025-05-19 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 11, 33, 21, 662664)),
        ),
    ]
