# Generated by Django 4.2.20 on 2025-06-07 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_borrowbook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 15, 38, 47, 81213)),
        ),
    ]
