# Generated by Django 4.2.20 on 2025-07-03 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_borrowbook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 13, 40, 49, 990587)),
        ),
    ]
