# Generated by Django 4.2.20 on 2025-03-30 16:16

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mail', models.CharField(error_messages={'unique': 'This mail address is already in the database.'}, max_length=255, unique=True)),
                ('userID', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
            ],
        ),
    ]
