# Generated by Django 4.2.20 on 2025-03-30 16:42

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('userID', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
