# Generated by Django 4.2.20 on 2025-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_remove_book_id_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_of_the_month',
            field=models.BooleanField(default=False),
        ),
    ]
